### ISSUE TITLE
nequip uses legacy e3nn-jax modules

### ISSUE THREAD

**Issue by M-R-Schaefer** [jax-md/jax-md#268]
The Nequip implementation in jaxmd uses the `FunctionalFullyConnectedTensorProduct` e3nn-jax which was recently moved to a different import path (`legacy`).
Due to the chain of imports jax_md -> energy -> nn -> _nn.nequip, importing jax_md immediately results in an import error:

```
...
/jax_md/_nn/e3nn_layer.py:214: in <module>
    from e3nn_jax import FunctionalFullyConnectedTensorProduct
E   ImportError: cannot import name 'FunctionalFullyConnectedTensorProduct' from 'e3nn_jax' (/home/mschaefer/miniconda3/envs/apax2/lib/python3.10/site-packages/e3nn_jax/__init__.py)
```

This can be fixed either by updating the nequip implementation or by using e3nn-jax version 0.19.1 or older.

**Comment by sinhon2030** [comment]
I am facing this issue too. I tried using e3nn-jax version 0.19.1 but I get the same error.

**Comment by Ali-Garhy** [comment]
Same here. Still keep getting the same error.

**Comment by Ali-Garhy** [comment]
It worked. Thanks for the fix!
